### ISSUE TITLE
Add User Fields (Waiting for review)

### ISSUE THREAD

**Issue by Guillem96** [Korakk/express-hackthon-backend#3]
Afegir aquets camps a l'usuari
- firstName (opcional)
- lastName (opcional)
- displayName (opcional)
- email (obligatori)
- photoURL (opcional/per defecte alguna image tipica de perfil sense imatge)

**Comment by Korakk** [comment]
email and photoURL, estan afegits, pero s'ha de mirar com controlar que un sol usuari només pugui tenir una imatge, perque ara per ara l'únic que he habilitat es que per crear un usuari hagis dafegir una imatge de forma obligada.  Obriré una altra issue amb el tema

**Comment by Korakk** [comment]
Added remaining user fields.

**Comment by Korakk** [comment]
Closing issue

**Comment by Korakk** [comment]
Before closing the issue, @Guillem96 review it. Branch --> oscar-modifications1
